# Generated by Django 5.2.14 on 2026-05-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requireddocument',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='Обязательный'),
        ),
    ]
